### ISSUE TITLE
resource actions

### ISSUE THREAD

**Issue by OrelFirefly** [pallets-eco/flask-classful#108]
Hi,

Lets assume I have a RESTful resource API created using `Flask-Classful`, e.g.
```python
from flask_classful import FlaskView

class MyResource(FlaskView):
    def get(self, id):
#...
```

and I have actions that I want to perform on said resource, e.g. get a list of a resource's related resources.
The REST way to do this would be making a request to `/myresource/1/related`.

I couldn't find a built-in way to do this in `Flask-Classful` right now, other than creating a new method in `MyResource` as such:
```python
class MyResource(FlaskView):
#...
    @route('/<id>/related')
    def list_resource_related(self, id):
#...
```

What I would have liked to have is the option to define this as a "sub-view", e.g.
```python
class MyResourceActions(FlaskView):
    def related(self):
#...
class MyResource(FlaskView):
#...
    sub_views = [
        {
         route_prefix: '/<id>/'
         view: MyResourceActions
         method: 'GET'
        }
    ]
#...
```

I've looked around, and I don't see any plans to add "sub-views"... Is this something people would like to see in flask-classful?

**Comment by hoatle** [comment]
I don't think we should implement this for flask-classful, it could make things more complicated.

**Comment by OrelFirefly** [comment]
Can you elaborate on where you expect complications? I have a simple solution in mind in terms of interface.

**Comment by moshewe** [comment]
It's like `express.js` routers mounting one on top of the other.

**Comment by hoatle** [comment]
I meant the complication added/changed to the source code and the maintenance cost of the additional feature. If you could propose, implement and see if someone is interested in using and maintaining it, it would be great for me to consider to merge that feature.

**Comment by z3ugma** [comment]
@OrelFirefly here's how I accomplish this.

Specify a variable in the route_prefix of a view. This variable is then exposed as a `kwarg` to your route functions:


```
from flask_classful import FlaskView

class NotesView(FlaskView):
    route_prefix = "/customer/<customer_id>/"

    def new(self, **kwargs):
        return render_template("note/new.html")

    def get(self, id, **kwargs):
        print(kwargs, note_id)
        # >>>kwargs: {'customer_id': 'foo'}
        # >>>note_id: the variable passed in this route. 
        note_model = {"customer_id": kwargs['customer_id'], "note_id": note_id}
        return render_template("note/show.html")
```

When running `flask routes` at the command line you can see the subresourcing style:
```
Endpoint                  Methods  Rule
------------------------  -------  ----------------------------
CustomerView:get          GET      /customer/<customer_id>/

NotesView:get             GET      /customer/<customer_id>/notes/<note_id>/
NotesView:new             GET      /customer/<customer_id>/notes/new/
```

**Comment by moshewe** [comment]
That's a nice hack, but what Class triggers such as validations on routes? I'd want to inherit those from the parent class. Maybe a helper function that takes all methods and wraps them so that you don't have to do the wiring yourself? That's the way I'd go. Haven't touched Flask in a while though so I'm rusty.
