### ISSUE TITLE
Modularity best practicies

### ISSUE THREAD

**Issue by strizhechenko** [pallets-eco/flask-classful#121]
Hi!

I'm trying to use flask-classful instead of flask-blueprints. It's great, but I miss one thing - nested `templates` folders for each blueprint which provide project structure like:

``` 
ducks/
    templates/
        ducks.html
    __init__.py
quotes/
    templates/
        quotes.html
    __init__.py
app.py
```
and it leads to one shared `templates` folder, like:

``` 
templates/
    ducks.html
    quotes.html
ducks.py
quotes.py
app.py
```

which will become a mess if there will be more and more views. What is the way to avoid it?

**Comment by foarsitter** [comment]
Combine the usage of `flask-blueprints` with `flask-classful`. Both libraries fulfill al complete different purpose imho and are complementary to each other.
