### ISSUE TITLE
swagger for flask classful

### ISSUE THREAD

**Issue by weiztech** [pallets-eco/flask-classful#128]
I'd like to know if it possible to have something like autogenerate swagger while using flask-classfull.

**Comment by hoatle** [comment]
AFAIK, there is no support to autogenerate swagger.

**Comment by dev-rijan** [comment]
I made a simple package   [Flask-classful-apispec](https://github.com/dev-rijan/flask-classful-apispec) to auto-generate open API specifications based on marshmallow apispec.
