### ISSUE TITLE
Unable to call class multiple time

### ISSUE THREAD

**Issue by thesunRider** [pallets-eco/flask-classful#129]
I have been trying to build a flask-classful app,
The problem is I am unable to create more than one instance of the API
An error is thrown by the flask,

`Traceback (most recent call last):
  File "test1.py", line 27, in <module>
    qt2.register(app)
  File "C:\Python3\lib\site-packages\flask_classful.py", line 157, in register
    app.add_url_rule(
  File "C:\Python3\lib\site-packages\flask\app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Python3\lib\site-packages\flask\app.py", line 1282, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: QuotesView:index`

I know that the error is thrown due to declaration of same function name and route,I am able to overcome the problem of routename by adding a random value as padding to the route.,But I have no idea what to do about the function naming.

`
 from flask import Flask
 import random
 from flask_classful import FlaskView,route

 quotes = [
    "A noble spirit embiggens the smallest man! ~ Jebediah Springfield",
    "If there is a way to do it better... find it. ~ Thomas Edison",
    "No one knows what he can do till he tries. ~ Publilius Syrus"
 ]

 app = Flask(__name__)

 class QuotesView(FlaskView):
    id = None

    @route("/"+str(random.randint(0,10000000)), methods=['GET', 'POST'])
    def index(self):
        return "<br>".join(quotes)

    def somestuff(self):
        self.id = random.randint(0,100);

 qt = QuotesView()
 qt.register(app)

 qt2 = QuotesView()
 qt2.register(app)

 if __name__ == '__main__':
     app.run()
`

If possible please suggest a work around.

**Comment by janmpeterka** [comment]
Hey @thesunRider , I'm not really sure what you want to achieve here.
Can you describe what your expected functionality is?
I don't really understand why would you register the same view more times.

**Comment by thesunRider** [comment]
I am using this to create an api for twilio,Whenever a guy calls in,the application redirects him to his specific class that was dynamically generate.

So what I want is to create separate instances of the same class that goto different routes whenever each call is being made.
I know this would be memory intensive but for now its not for production use! Hope you understand my use case.

**Comment by janmpeterka** [comment]
Not really understanding the use-case here, but cannot it be achieved using <arg> in your url / route?

Something like
```
@route("/<unique_token>", methods=['GET', 'POST'])
def index(self, unique_token):
   return "<br>".join(quotes)
```
?

Now you can generate this key elsewhere and redirect to this route e.g. `/index/26421256`.

**Comment by thesunRider** [comment]
Is there any way to call the class twice,on each call,let the routes be assigned different but the function names should remain the same

**Comment by janmpeterka** [comment]
I'm sorry, I really don't understand why you want to do that.
Maybe try to detail what function of your app should be and then we can find a way to do that.

**Comment by thesunRider** [comment]
Sure!

This is the file which calls the twilio API I just made

**File no 1.**
```
import time,random,uuid
from twilioplayer import PlayAudio,AudioPlayer
from flask_classful import FlaskView
from flask import Flask,request
from twilio.twiml.voice_response import VoiceResponse, Gather


database_url = 'http://myipaddress'

app = Flask(__name__)


response_main = VoiceResponse()

calls_inline = []

@app.route("/call_status", methods=['GET', 'POST'])
def callstat():
	print("Printing call status")
	print(calls_inline)
	response_main = VoiceResponse()
	return str(response_main)


@app.route("/voice", methods=['GET', 'POST'])
def voice():
	player = PlayAudio(app,response_main,"sample_audio", database_url)
	player2 = PlayAudio(app,response_main,"sample_audio", database_url)
	data = request.form.to_dict(flat=False)
	caller_no = data['From'][0]
	calls_inline.append({"no":caller_no,"id":player.id_base})
	return str(player.twilio_obj)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```


And this is the API I wrote for playback:

**File no .2**
```
from flask import Flask,send_file, make_response ,request
from twilio.twiml.voice_response import VoiceResponse, Gather
from pydub import AudioSegment
from pydub.playback import play
import io,random,configparser,time
from flask_classful import FlaskView,route
import requests,uuid,random


class PlayAudio():
	twilio_obj = None
	id_base = None
	
	def __init__(self,app,twilio_obj,audio_id,database_url):
		route_base = "/" + str(uuid.uuid4()).replace("-","") + str(random.randint(10, 5000))
		AudioPlayer_instance =  globals()['AudioPlayer']
		AudioPlayer_instance.register(app,route_base=route_base,init_argument={'base':route_base,'id':audio_id, 'db':database_url})
		twilio_obj.redirect(route_base + '/voice')
		self.twilio_obj = twilio_obj
		self.id_base = route_base
		#print("finished calling initialier")


class  AudioPlayer(FlaskView):
	route_mainbase = '/call_audio'

	
	#Reading INI File which contains audio info,We dont want all audio info to be kept at one place
	config_file = 'config.ini'
	config = configparser.ConfigParser()
	config.read(config_file)

	list_data = {}

	#Audio id which will be played this is specified for portability
	audio_id = 'sample_audio'

	#url to ask for audio
	url = 'http://localhost'

	#this is set to compensate for overall time delay (note that there is a function which gives more control)
	time_compensate = 0
	time_delaycompensate = 0.5

	#audio length in seconds,this is the time that gather uses for timeout
	audio_length = 103.0

	#used to set increments in speed of audio
	delta_time = 0.25

	#Use this to set your range of audio speed
	time_speed = {'min':1,'max':2}

	#amount of time to skip the audio
	skip_time = 15

	#extra variables
	#audio = AudioSegment.from_wav(config['audio'][audio_id])

	def __init__(self, init_arg):
		self.route_mainbase = init_arg['base']
		self.audio_id = init_arg['id']
		self.url = init_arg['db']
		#self.audio_getlength()
		#print("Setting all variables")
		#print(self.url)
		#print('_________________')


	def index(self):
		return "<br>Nothing In here"

		
	@route("/voice", methods=['GET', 'POST'])
	def voice(self):
		return 0 #return some more stuff

	@route("/check_keypress", methods=['GET', 'POST'])
	def check_key(self):
		return 0 #return some stuff

	@route("/call_status", methods=['GET', 'POST'])
	def call_status(self):
		return 0 #return some stuff


	#this is called only when method 1 is enabled,currently using method2
	@route("/giveme_audio", methods=['GET', 'POST'])
	def giveme_audio(self):
		return 0 #return some stuff

	def play_audio(self,response,loop_details):
		#playback some audio
		return response


	def calculate_serverparams(self,ary):
		return 0 #return some stuff

	def delay_compensator(self,server_params,loop_details):
		return 0 #return some stuff


	def audio_getlength(self):
		return 0 #return some stuff



```

So in here everytime a call comes in, **File no 1** creates a new class instance and redirects the user to that specific class and an **audio according which the user has already set (its the users preference)** is played (this is passed to **File no 2** as audio_id) ,this is achieved by dynamically creating a  new class instance everytime a user calls in ,and whenever he calls ,a dedicated route for that specific user is made by the flask application,But in here creating another instance of the same class is not possible as even though the routes are created different the function names in the classes remains the same,I need a work around for this,Any help in any direction is greatly appreciated ,Thanks

**Comment by janmpeterka** [comment]
I'm sorry, as I'm not familiar with Twilio, I don't really understand what are you trying to achieve and why are you trying to do it this way.
It doesn't make much sense to dynamically generated routes to me in general, as it adds some functionality and use case that seems a bit obscured and non-explicit (opposing "Explicit is better than implicit" in [Zen of Python](https://www.python.org/dev/peps/pep-0020/). I don't see why on-demand generated URLs cannot be managed via attribute, as I would do in token-based authentication or similar).
Maybe someone else will help, or we can try to have a chat on stackoverflow (which might me good place to ask for general solution for this).
Hope you will manage to solve this.

**Comment by zgoda** [comment]
Register under different endpoint, see https://werkzeug.palletsprojects.com/en/1.0.x/routing/#werkzeug.routing.Rule, doc: http://flask-classful.teracy.org/#a-few-words-on-register
