### ISSUE TITLE
Thoughts on moving this repo to pallets-eco so it can be picked up by contributors?

### ISSUE THREAD

**Issue by nickjj** [pallets-eco/flask-classful#147]
Hi,

This extension has Werkzeug compatibility issues that prevent going past 2.1. There has been a PR (https://github.com/teracyhq/flask-classful/pull/145) to address 2.2 compatibility since August 2022 but there's been no response from the current maintainer of this project on merging it. Flask / Werkzeug is also currently at 2.3.X at the time of making this issue.

I'm really appreciative of this library (thanks @teracyhq). I still quote it as having some of the best docs for any software project and I personally had a great ~5 year run with it.

As someone who also does open source work, I understand it for maintainers to bow out. If that's the case here, what do you think about moving this repo to [pallets-eco](https://github.com/pallets-eco) so it can be picked up by contributors? After bringing this up on IRC, @davidism (core maintainer of Flask and Pallets libraries) suggested this.

**Comment by hoatle** [comment]
Hello @nickjj,

Thank you for your information. We don't have enough resources to maintain this project at present, so it's better to move it to pallets-eco. I believe that is the best way to move this project forward.

**Comment by nickjj** [comment]
In order to do that, it would require the current owner of this repo to transfer it. I see you have Member status, do you have admin access to this repo?

**Comment by hoatle** [comment]
yes, I do

**Comment by nickjj** [comment]
I'm not a core maintainer of Flask and never transferred a repo so I'm not sure what the process would look like.

But, I think it might work something like this when you're ready to transfer:

- Visit https://github.com/teracyhq/flask-classful/settings and then goto the danger section to "Transfer ownership".
- You'd pick "Specify an organization or username" and choose "pallets-eco", which is https://github.com/pallets-eco/
- It wouldn't hurt to add a note, perhaps something like "David suggested moving this project here to be picked up by contributors."
- Click the transfer this repo button
    - WARNING: I'd suggest not doing this until reading this comment in full

I haven't done this process first hand so it's hard to say what happens next. Maybe the owner of pallets-eco will receive an invite and then they can confirm your submission and upon doing that this repo will be moved to `pallets-eco/flask-classful` and you'd have contributor access. The docs on https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository has more information. For example, the old URL will still work with redirects as long as teracyhq doesn't make a new `flask-classful` repo in the future.

At this point contributors to `pallets-eco` will be able to contribute to this project. I can't speak for anyone but I wouldn't anticipate it being a bull in a china shop scenario where they start adding a ton of things without discussion. It's still your project, it's just now a few more folks will be able to review and merge PRs, help with releases and contribute back to the project.

Here's a couple of things to consider, potentially before transferring the repo:

- What level of involvement do you want in the project? For example, do you want to be `@` mentioned before any new PRs are merged or releases are made?
- This is all grey areas for me but I think some level of PyPI access would need to be given to selected folks in pallets-eco who would be responsible for creating new releases if you want that process to be handled by anyone other than you

@davidism Can you clarify if the above is accurate?

@hoatle There's no pressure here. Pending David's response, you can take it here from at your discretion. Thanks a lot for making this extension!

**Comment by davidism** [comment]
I think I might need to add you to the org first, so you have permission to transfer, but try it first without that. You'll still be an owner of the repo, but so with the Pallets owners. The idea is we can give other interested contributors commit permission, and then a much smaller group publish permission. You'll need to add me to the project on PyPI (and TestPyPI if you use it), and Read the Docs, my username is davidism on both.

**Comment by hoatle** [comment]
I got this error:

![image](https://user-images.githubusercontent.com/83062/236281216-0ff3cd5d-3108-4b06-b1c3-b6cbda9a2158.png)

**Comment by davidism** [comment]
I've sent you an invite, then you should be able to complete the transfer.

**Comment by hoatle** [comment]
the project is transferred now

**Comment by davidism** [comment]
Thanks! Please add me (davidism) to PyPI so we can publish new releases.

**Comment by hoatle** [comment]
@davidism PyPi project invitation was sent.

**Comment by davidism** [comment]
Thank you. For community members who are interested in contributing, please join us at https://discord.gg/pallets in the #pallets-eo channel.

**Comment by darkcircle** [comment]
so ... Is it going on update?

**Comment by nickjj** [comment]
It was switched over https://github.com/pallets-eco/flask-classful about a month ago.

**Comment by darkcircle** [comment]
> It was switched over https://github.com/pallets-eco/flask-classful about a month ago.

Yes. I'm looking at there. all things seem to be moved correctly.
