### ISSUE TITLE
Please mark this project as public archive

### ISSUE THREAD

**Issue by Corbie-42** [pallets-eco/flask-classful#150]
@hoatle as the development in this project is no longer going on, would you please mark it as public archive?

**Comment by davidism** [comment]
It has been transferred to @pallets-eco, which is intended to allow community maintenance, similar to [Jazzband](https://jazzband.co). I'm currently working on more resource to help people get involved, but this is ongoing with multiple projects at once. If you're a contributor to this project who can commit to ongoing maintenance and wants to get write permission, please get in touch at the Pallets Discord server, https://discord.gg/pallets.
