### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by Flix6x** [pallets-eco/flask-classful#152]
[This workflow](https://github.com/pallets-eco/flask-classful/actions/runs/6003454262/job/16281973631) failed on:
```
remote: Permission to pallets-eco/flask-classful.git denied to github-actions[bot].
```

As far as I can tell, it looks like we can't update the documentation until we sort this out.

**Comment by davidism** [comment]
Fixed by #158, https://flask-classful.readthedocs.io
