### ISSUE TITLE
Standard repo tidying.

### ISSUE THREAD

**Issue by hjc** [pallets-eco/flask-classful#75]
@hoatle - I think adding some small docs and standard OSS repo items would be good, such as a pull request template, contributor's guidelines, etc.

Let me know your thoughts and if you have something you want to do for this in mind, otherwise I can slowly get it done.

**Comment by hoatle** [comment]
@hjc yeah, that's good to me. I guess we can follow the guides here to update for our repo: https://opensource.guide/

**Comment by hjc** [comment]
Sweet! I'll check this out in the next few days.
