### ISSUE TITLE
define the roadmap for v0.15.0

### ISSUE THREAD

**Issue by hoatle** [pallets-eco/flask-classful#77]
v0.14.0 is going to be released soon, it's time for us to figure out what's next for flask-classful.

- The first thing in my mind is to create more example, tutorials and integration examples, best practices for flask-classful to build robust REST APIs.

- What's next? We need to figure this out together, there are some issues that we need to discuss to see if it's a fit for flask-classful (for example, IOC issue, etc).

**Comment by hjc** [comment]
First off, totally agreed about examples, tutorials, and the like. Fleshing out the documentation and making sure we're documenting all of our key member variables and methods is what I was going to advocate for.

In terms of features, I haven't used Classful in awhile, so I'm not in dire need of a big feature. Right now I'm kind of without inspiration. If something hits me, I'll certainly let you know.

@hoatle - what were you thinking of adding? While I hate how IoC is done in Python, I don't think that's a proper fit for the library, that should probably be it's own thing.

**Comment by hoatle** [comment]
@hjc yeah, so let's wait to see if there is anything that we need to add to, otherwise, let's keep it stable enough for now.

**Comment by hoatle** [comment]
@hjc for the IoC, I agree that it's not fit for the lib, just to mention that there is an issue for that https://github.com/teracyhq/flask-classful/issues/48

**Comment by hoatle** [comment]
we should check out the issues from https://github.com/apiguy/flask-classy/issues to see if we can see and support for more use cases there.

**Comment by kristofgilicze** [comment]
I have been using Flask-Classful, it comes in really handy!

It would be great to have the ability to create sub views.  
Let's say i have a data model where i have top level model like 'Measure' and then i have 'Measure runs'.

**Comment by AMNeumann** [comment]
Is there any timeline for v0.15.0?

**Comment by hoatle** [comment]
@AMNeumann there is no scope and features/changes to propose for v0.15.0 so no release date yet.

The latest release is v0.14.2, you can see it here: https://github.com/teracyhq/flask-classful/releases

**Comment by shevron** [comment]
It would be awesome if we can have https://github.com/teracyhq/flask-classful/pull/86 released as 0.15 (or even as (0.14.3 for that matter) - at least for me it is a really useful feature and I'm using a non-release version just to have it in several projects. Awesome project BTW, not here to complain just to suggest, would love to help make a release if there are specific things to be done for that :-)

**Comment by gabloe** [comment]
Is there going to be a new release soon with #86?

**Comment by hoatle** [comment]
With some minor changes but not yet fully tested so I'm going to release the current code base as v0.15.0-beta.1

**Comment by hoatle** [comment]
https://pypi.org/project/Flask-Classful/0.15.0b1/ is released, hope you guys can continue checking, contributing and we can move toward the 0.15.0 release
